export default class ActionTypes {
    static BITFINEX = {
        CHANGE_BITFINEX_CANDLES: 'CHANGE_BITFINEX_CANDLES',
        CHANGE_BITFINEX_SETUP: 'CHANGE_BITFINEX_SETUP',
        ADD_NEW_CANDLES_PACKAGE: 'ADD_NEW_CANDLES_PACKAGE'
    }
}
